version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    target-branch: "develop"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "chore"
      - "dependencies"
      - "semver:patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
    target-branch: "develop"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci(deps)"
    labels:
      - "ci"
      - "dependencies"
      - "semver:patch"
